apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: payload-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: tttttt
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: payload-secrets
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: payload-app
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3001
